name: BLAHAJ-rs
version: '1.0.0'
summary: Gay sharks at your local terminal.
base: core18
description: |
  BLAHAJ-rs is the Rust re-implementation of the original BLAHAJ. It is
  fast, and can flush stdout unlike the Crystal language.
apps:
        BLAHAJ-rs:
                command: bin/blahaj

grade: stable
confinement: strict

parts:
  blahaj:
          source: https://github.com/yoshisaac/BLAHAJ-rs.git
          plugin: rust
